spring:
  application:
    name: fa
  datasource:
    url: jdbc:mysql://localhost:3306/fa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 23456789

logging:
  level.com.f.fa: debug
